name: Deploy Backend to Azure App Service (Maven)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # If your pom.xml is NOT at the repo root, uncomment the next line and set the folder:
      # working-directory: backend

      - name: Build with Maven
        run: mvn -B -DskipTests package
        # working-directory: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: stackarc-api-cjhwakfebnd6bqab
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: target/*.jar
          # If you set working-directory above, change package to: backend/target/*.jar
