name: Build and deploy JAR to Azure Web App - stackarc-api-cjhwakfebnd6bqab

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Detect build tool (Maven vs Gradle)
        id: detect
        shell: bash
        run: |
          set -e
          if [ -f "pom.xml" ]; then
            echo "BUILD_TOOL=maven" >> $GITHUB_ENV
            echo "Detected Maven"
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "BUILD_TOOL=gradle" >> $GITHUB_ENV
            echo "Detected Gradle"
          else
            echo "❌ Neither pom.xml nor build.gradle(.kts) found at repo root."
            echo "Make sure your backend project with its build file is at the repository root."
            exit 1
          fi

      # --- Maven path ---
      - name: Build with Maven
        if: env.BUILD_TOOL == 'maven'
        run: mvn -B -DskipTests clean package

      # --- Gradle path ---
      - name: Prepare Gradle (cache)
        if: env.BUILD_TOOL == 'gradle'
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        if: env.BUILD_TOOL == 'gradle'
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          else
            echo "❌ Gradle wrapper (./gradlew) not found. Please add the wrapper to your repo."
            echo "Run locally: gradle wrapper"
            exit 1
          fi

      - name: Build with Gradle
        if: env.BUILD_TOOL == 'gradle'
        run: ./gradlew build -x test

      - name: Locate built JAR
        id: jar
        run: |
          set -e
          JAR_PATH="$(ls -1 target/*.jar 2>/dev/null || true)"
          if [ -z "$JAR_PATH" ]; then
            JAR_PATH="$(ls -1 build/libs/*.jar 2>/dev/null || true)"
          fi
          if [ -z "$JAR_PATH" ]; then
            echo "❌ Could not find JAR in target/ or build/libs/. Failing."
            exit 1
          fi
          echo "Found JAR: $JAR_PATH"
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ env.JAR_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0E145546C783447C805B0C0CF0E97D43 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_67D4F51B269448558F3A397E308B86D1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06251A6175C64CBAB43EC3517F304AD0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stackarc-api-cjhwakfebnd6bqab'
          slot-name: 'Production'
          package: '*.jar'
